name: CI 

on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
  
jobs: 
  build-and-test: 
    runs-on: macOS-14

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app
    
    - name: Build and test 
      run: xcodebuild clean build test -workspace MorseCodeApp.xcworkspace -scheme "MorseCodeApp" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" ONLY_ACTIVE_ARCH=YES
