name: CI 

on: 
  push: 
    branches: [ "main" ] 
  pull_request: 
    branches: [ "main" ] 
  
jobs: 
  build-and-test: 
    runs-on: macOS-14

    steps:
    - uses: actions/checkout@v3
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
          access_token: ${{ github.token }}
          
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
          
    - name: Build and test 
      run: xcodebuild clean build test -workspace MorseCodeApp.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0.1" ONLY_ACTIVE_ARCH=YES
