name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3

    - name: Install Apple Certificate
      uses: apple-actions/import-codesigning-certs@v1
      with: 
        p12-file-base64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}

    - name: Install Provisioning Profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version    

    - name: Build and Archive
      run: |
        xcodebuild clean archive -sdk iphoneos -workspace MorseCodeApp.xcworkspace -scheme "MorseCodeApp" -configuration "Release" -derivedDataPath "DerivedData" -archivePath "DerivedData/Archive/MorseCodeApp.xcarchive"
    
    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath DerivedData/Archive/MorseCodeApp.xcarchive -exportOptionsPlist .github/workflows/ExportOptions.plist -exportPath DerivedData/ipa

    - name: Upload to App Store
      run: xcrun altool --upload-app --type ios --file "DerivedData/ipa/MorseCodeApp.ipa" --username "${{ secrets.APPSTORE_USERNAME }}" --password "${{ secrets.APPSTORE_PASSWORD }}" --verbose
